import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { cookies } from "next/headers";
import Darkmode from "./Darkmode";
/* import { useState } from "react"; */
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  let res = cookies().get("mode");
  console.log(res,'쿠키이름');

  /*   const [dark, setDark] = useState("dark"); */

  return (
    <html lang="en">
      <body className={res.value == 'dark' ? 'dark-mode' : ''}>
        {" "}
        <div className="navbar">
          <Link href="/" className="logo">
            Appleforum
          </Link>
          <Link href="/list">List</Link>
          {session ? (
            <span>{session.user.name} 님 안녕하세요 </span>
          ) : (
            <LoginBtn />
          )}
          <Darkmode />
        </div>{" "}
        {children}
      </body>
    </html>
  );
}
